---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user 
  become: yes
  become_user: root 
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state:  latest

- name: update LB server
  hosts: lb 
  remote_user: ubuntu
  become: yes
  become_user: root 
  tasks:
    - name: Update apt repo 
      apt: 
        update_cache: yes
    - name: ensure wireshark is at the latest version
      apt:  
        name: wireshark
        state:  latest

- name: Create a directory
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root 
  tasks:
    - name: Create a directory
      file:
      path: /var/test
      state: directory
      mode: '0755'

- name: Create a file
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root 
  tasks:
    - name: Create a file
      file:
      path: /var/test/ans_file
      state: touch
      mode: u=rwx,g=r,o=r


